// mf---web-approach/team--page-home/src/app/components/ListItem/ListItem.tsx
import React from 'react';
import Item from '../../core/model/Item';
import { pricetoEuro } from '../../utils/pricetoEuro';
import { DETAIL_URL } from '../../../config';
import './ListItem.scss';

export interface ListItemProps {
	item: Item
}

const ListItem: React.FC<ListItemProps> = (props) => {

	var divStyle = {
		backgroundImage: `url(${props.item.images[0]})`,
	}

	return <a href={`${DETAIL_URL}/detail/${props.item.id}`} className="list-item">
			<div className="list-item--item" style={divStyle}>
				<div className="item-info">
					{`${props.item.name} - ${pricetoEuro(props.item.price)}`}
				</div>
			</div>
		</a>;
}

export default ListItem;

// mf---spa-composition/team-list/src/components/ListItem.vue
<template>
  <a v-if="item" :href="'#/detail/' + item.id" class="list-item">
		<div class="list-item--item" :style="{ backgroundImage: 'url(' + item.images[0] + ')' }">
			<div class="item-info">
				{{item.name}} - {{item.price}}
			</div>
		</div>
	</a>
</template>

<script>
export default {
	name: 'list-item',
	props: {
		item: Object
	},
}
</script>

<style lang="scss">
.list-item {
	color: black;
	
	.list-item--item {
		width: 100%;
		height: 100%;
		overflow: hidden;
		background-size: cover;
		background-position: center;
		position: relative;
	
		.item-info {
			position: absolute;
			bottom: 0;
			left: 0;
			right: 0;
			height: 50px;
			text-align: center;
			background-color: white;
		}
	}
}
</style>
