// mf---web-approach/team--page-home/src/app/components/NavigationBar/NavigationBar.tsx
import React from 'react';
import {
  Link,
} from "react-router-dom";
import './NavigationBar.scss';
import classnames from 'classnames'
import Gender from '../../utils/Gender';
import Api from '../../core/api';

export interface NavigationBarProps {
	gender: Gender
}

export interface NavigationBarState {
	basketCount: number
}

export default class NavigationBar extends React.Component<NavigationBarProps, NavigationBarState> {
	
	state: NavigationBarState = {
		basketCount: 0
	}

	componentDidMount() {
		this.fetchBasket()
	}

	private async fetchBasket() {
		const resp = await Api.getFromServer<any>("basket", true)
		if (resp.success) {
			this.setState({
				basketCount: resp.data.content.length as number
			})
		}
	}

	render() {
		return (
			<nav>
				<ul>
					<li className={classnames({"active": this.props.gender === Gender.MEN})}>
						<Link to="/men">Herren</Link>
					</li>
					<li className={classnames({"active": this.props.gender === Gender.WOMAN})}>
						<Link to="/woman">Damen</Link>
					</li>
					<li className={classnames("basket")}>
						<a href="https://www.inovex.de">Warenkorb: {this.state.basketCount}</a>
					</li>
				</ul>
			</nav>
		);
	}
}

// mf---web-approach/team--page-detail/src/components/NavigationBar.vue
<template>
  <nav>
		<ul>
			<li>
				<a :href="HOME_URL + '/#/men'">Herren</a>
			</li>
			<li>
				<a :href="HOME_URL + '/#/woman'">Damen</a>
			</li>
			<li class="basket">
				<a href="https://www.inovex.de">Warenkorb: {{basketCount}}</a>
			</li>
		</ul>
	</nav>
</template>

<script>
import Api from '../core/api'
import { HOME_URL } from '../config'

export default {
	name: 'NavigationBar',
	data: function() {
		return {
			basketCount: 0,
			HOME_URL: HOME_URL
		}
	},
	created: async function() {
		this.fetchBasket()
		document.addEventListener("basket", () => this.fetchBasket())
	},
	methods: {
		fetchBasket: async function() {
			var resp = await Api.getFromServer("basket", true)
			if (resp.success) {
				this.basketCount = resp.data.content.length
			}
		}
	}
}
</script>

<style lang="scss">
nav {
  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #003C7E;
  }

  li {
    float: left;
    border-right:1px solid #bbb;

    &.basket {
      float: right;
    }
  }

  li:last-child {
    border-right: none;
  }

  li {
    a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      border: none;
      background-color: transparent;
      cursor: pointer;

      &:focus {
        outline: none;
      }
    }

    &:hover:not(.active) {
      background-color: #111;
    }

    &.active {
      background-color: #2E7D32;
    }
  }
}
</style>
